# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c301ffc2c48b023e8590a1715b34d5d"
name = "Track My Order"
handle = "track-my-order"
application_url = "https://track-my-order-alpha.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"


  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders"

[auth]
redirect_urls = ["https://track-my-order-alpha.vercel.app/auth/callback", "https://track-my-order-alpha.vercel.app/auth/shopify/callback", "https://track-my-order-alpha.vercel.app/api/auth/callback"]

[pos]
embedded = false
